version: '3'

services:
  server:
    build:
      context: ./app/server
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    environment:
      - FLASK_ENV=development

  react_web:
    build:
      context: ./app/web
      dockerfile: Dockerfile
    ports:
      - '8081:80'
    depends_on:
      - server
